import 'dart:async';

import 'package:flutter/material.dart';

import '../../../controller/controllers/editor-controller.dart';
import '../../../documents/models/attribute.model.dart';
import '../../../documents/models/attributes/attributes.model.dart';
import '../../../documents/models/style.model.dart';
import '../../../documents/services/attribute.utils.dart';
import '../../../shared/models/editor-icon-theme.model.dart';
import '../../../shared/state/editor-state-receiver.dart';
import '../../../shared/state/editor.state.dart';
import '../../models/toggle-style-button-builder.type.dart';
import '../toolbar.dart';

// ignore: must_be_immutable
class ToggleStyleButton extends StatefulWidget with EditorStateReceiver {
  final AttributeM attribute;
  final IconData icon;
  final double iconSize;
  final Color? fillColor;
  final double buttonsSpacing;

  final EditorController controller;
  final ToggleStyleButtonBuilder childBuilder;
  final EditorIconThemeM? iconTheme;

  // Used internally to retrieve the state from the EditorController instance to which this button is linked to.
  // Can't be accessed publicly (by design) to avoid exposing the internals of the library.
  late EditorState _state;

  @override
  void setState(EditorState state) {
    _state = state;
  }

  ToggleStyleButton({
    required this.attribute,
    required this.icon,
    required this.buttonsSpacing,
    required this.controller,
    this.iconSize = defaultIconSize,
    this.fillColor,
    this.childBuilder = defaultToggleStyleButtonBuilder,
    this.iconTheme,
    Key? key,
  }) : super(key: key) {
    controller.setStateInEditorStateReceiver(this);
  }

  @override
  _ToggleStyleButtonState createState() => _ToggleStyleButtonState();
}

class _ToggleStyleButtonState extends State<ToggleStyleButton> {
  bool? _isToggled;
  StreamSubscription? _refreshListener;

  StyleM get _selectionStyle => widget.controller.getSelectionStyle();

  @override
  void initState() {
    super.initState();
    _isToggled = _getIsToggled(_selectionStyle.attributes);
    _subscribeToRefreshListener();
  }

  @override
  Widget build(BuildContext context) {
    return widget.childBuilder(
      context,
      widget.attribute,
      widget.icon,
      widget.buttonsSpacing,
      widget.fillColor,
      _isToggled,
      _toggleAttribute,
      widget.iconSize,
      widget.iconTheme,
    );
  }

  @override
  void didUpdateWidget(covariant ToggleStyleButton oldWidget) {
    super.didUpdateWidget(oldWidget);

    // If a new controller was generated by setState() in the parent
    // we need to subscribe to the new state store.
    if (oldWidget.controller != widget.controller) {
      _refreshListener?.cancel();
      widget.controller.setStateInEditorStateReceiver(widget);
      _subscribeToRefreshListener();
      _isToggled = _getIsToggled(_selectionStyle.attributes);
    }
  }

  @override
  void dispose() {
    _refreshListener?.cancel();
    super.dispose();
  }

  // === PRIVATE ===

  void _subscribeToRefreshListener() {
    _refreshListener = widget._state.refreshEditor.refreshEditor$.listen(
      (_) => _didChangeEditingValue(),
    );
  }

  void _didChangeEditingValue() {
    setState(
      () => _isToggled = _getIsToggled(_selectionStyle.attributes),
    );
  }

  bool _getIsToggled(Map<String, AttributeM> attrs) {
    if (widget.attribute.key == AttributesM.list.key) {
      final attribute = attrs[widget.attribute.key];

      if (attribute == null) {
        return false;
      }

      return attribute.value == widget.attribute.value;
    }

    return attrs.containsKey(widget.attribute.key);
  }

  void _toggleAttribute() {
    widget.controller.formatSelection(
      _isToggled!
          ? AttributeUtils.clone(widget.attribute, null)
          : widget.attribute,
    );
  }
}

Widget defaultToggleStyleButtonBuilder(
  BuildContext context,
  AttributeM attribute,
  IconData icon,
  double buttonsSpacing,
  Color? fillColor,
  bool? isToggled,
  VoidCallback? onPressed, [
  double iconSize = defaultIconSize,
  EditorIconThemeM? iconTheme,
]) {
  final theme = Theme.of(context);
  final isEnabled = onPressed != null;
  final iconColor = isEnabled
      ? isToggled == true

          // You can specify your own icon color
          ? (iconTheme?.iconSelectedColor ?? theme.primaryIconTheme.color)
          : (iconTheme?.iconUnselectedColor ?? theme.iconTheme.color)
      : (iconTheme?.disabledIconColor ?? theme.disabledColor);
  final fill = isEnabled
      ? isToggled == true

          // Selected icon fill color
          ? (iconTheme?.iconSelectedFillColor ?? theme.toggleableActiveColor)

          // Unselected icon fill color :
          : (iconTheme?.iconUnselectedFillColor ?? theme.canvasColor)

      // Disabled icon fill color
      : (iconTheme?.disabledIconFillColor ?? (fillColor ?? theme.canvasColor));

  return IconBtn(
    highlightElevation: 0,
    hoverElevation: 0,
    buttonsSpacing: buttonsSpacing,
    size: iconSize * iconButtonFactor,
    icon: Icon(
      icon,
      size: iconSize,
      color: iconColor,
    ),
    fillColor: fill,
    onPressed: onPressed,
    borderRadius: iconTheme?.borderRadius ?? 2,
  );
}
