import 'dart:async';

import 'package:flutter/material.dart';

import '../../../controller/controllers/editor-controller.dart';
import '../../../document/models/attributes/attribute.model.dart';
import '../../../document/models/attributes/attributes-aliases.model.dart';
import '../../../document/models/attributes/attributes.model.dart';
import '../../../document/services/nodes/attribute.utils.dart';
import '../../../editor/services/run-build.service.dart';
import '../../../shared/models/editor-icon-theme.model.dart';
import '../../../shared/state/editor-state-receiver.dart';
import '../../../shared/state/editor.state.dart';
import '../../../styles/services/styles.service.dart';
import '../../services/toolbar.service.dart';
import '../toolbar.dart';
import 'shared/toggle-button.dart';

// Toggles checkboxes on and off.
// ignore: must_be_immutable
class ToggleCheckListButton extends StatefulWidget with EditorStateReceiver {
  final IconData icon;
  final double iconSize;
  final Color? fillColor;
  final EditorController controller;
  final AttributeM attribute;
  final EditorIconThemeM? iconTheme;
  final double buttonsSpacing;
  late EditorState _state;

  ToggleCheckListButton({
    required this.icon,
    required this.controller,
    required this.attribute,
    required this.buttonsSpacing,
    this.iconSize = defaultIconSize,
    this.fillColor,
    this.iconTheme,
    Key? key,
  }) : super(key: key) {
    controller.setStateInEditorStateReceiver(this);
  }

  @override
  _ToggleCheckListButtonState createState() => _ToggleCheckListButtonState();

  @override
  void cacheStateStore(EditorState state) {
    _state = state;
  }
}

class _ToggleCheckListButtonState extends State<ToggleCheckListButton> {
  late final RunBuildService _runBuildService;
  late final ToolbarService _toolbarService;
  late final StylesService _stylesService;

  bool? _isToggled;
  StreamSubscription? _runBuild$L;

  @override
  void initState() {
    _runBuildService = RunBuildService(widget._state);
    _toolbarService = ToolbarService(widget._state);
    _stylesService = StylesService(widget._state);

    super.initState();

    if (_attributes != null) {
      _isToggled = _getIsToggled(_attributes!);
    }

    _subscribeToRunBuild();
  }

  @override
  void dispose() {
    _runBuild$L?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => ToggleButton(
        context: context,
        icon: widget.icon,
        buttonsSpacing: widget.buttonsSpacing,
        fillColor: widget.fillColor,
        isToggled: _isToggled,
        onPressed: _toggleAttribute,
        iconSize: widget.iconSize,
        iconTheme: widget.iconTheme,
      );

  @override
  void didUpdateWidget(covariant ToggleCheckListButton oldWidget) {
    super.didUpdateWidget(oldWidget);

    // If a new controller was generated by setState() in the parent
    // we need to subscribe to the new state store.
    if (oldWidget.controller != widget.controller) {
      _runBuild$L?.cancel();
      widget.controller.setStateInEditorStateReceiver(widget);
      _subscribeToRunBuild();
      _isToggled = _getIsToggled(_attributes!);
    }
  }

  // === UTILS ===

  void _subscribeToRunBuild() {
    _runBuild$L = _runBuildService.runBuild$.listen(
      (_) => setState(() {
        _isToggled = _getIsToggled(_attributes!);
      }),
    );
  }

  Map<String, AttributeM>? get _attributes =>
      _stylesService.getSelectionStyle().attributes;

  bool _getIsToggled(Map<String, AttributeM> attrs) {
    final toggler = _toolbarService.getToolbarButtonToggler();
    var attribute = toggler[AttributesM.list.key];

    if (attribute == null) {
      attribute = attrs[AttributesM.list.key];
    } else {
      // Checkbox tapping causes selection to go to offset 0
      toggler.remove(AttributesM.list.key);
    }

    if (attribute == null) {
      return false;
    }

    return attribute.value == AttributesAliasesM.unchecked.value ||
        attribute.value == AttributesAliasesM.checked.value;
  }

  void _toggleAttribute() {
    final attribute = _isToggled!
        ? AttributeUtils.clone(AttributesAliasesM.unchecked, null)
        : AttributesAliasesM.unchecked;

    _stylesService.formatSelection(attribute);
  }
}
