import 'dart:async';

import 'package:flutter/material.dart';

import '../../../controller/controllers/editor-controller.dart';
import '../../../documents/models/attribute.model.dart';
import '../../../documents/models/attributes/attributes-aliases.model.dart';
import '../../../documents/models/attributes/attributes.model.dart';
import '../../../documents/models/style.model.dart';
import '../../../documents/services/attribute.utils.dart';
import '../../../shared/models/editor-icon-theme.model.dart';
import '../../../shared/state/editor-state-receiver.dart';
import '../../../shared/state/editor.state.dart';
import '../../models/toggle-style-button-builder.type.dart';
import '../toolbar.dart';

// ignore: must_be_immutable
class ToggleCheckListButton extends StatefulWidget with EditorStateReceiver {
  final IconData icon;
  final double iconSize;
  final Color? fillColor;
  final EditorController controller;
  final ToggleStyleButtonBuilder childBuilder;
  final AttributeM attribute;
  final EditorIconThemeM? iconTheme;
  final double buttonsSpacing;

  // Used internally to retrieve the state from the EditorController instance to which this button is linked to.
  // Can't be accessed publicly (by design) to avoid exposing the internals of the library.
  late EditorState _state;

  @override
  void setState(EditorState state) {
    _state = state;
  }

  ToggleCheckListButton({
    required this.icon,
    required this.controller,
    required this.attribute,
    required this.buttonsSpacing,
    this.iconSize = defaultIconSize,
    this.fillColor,
    this.childBuilder = defaultToggleStyleButtonBuilder,
    this.iconTheme,
    Key? key,
  }) : super(key: key) {
    controller.setStateInEditorStateReceiver(this);
  }

  @override
  _ToggleCheckListButtonState createState() => _ToggleCheckListButtonState();
}

class _ToggleCheckListButtonState extends State<ToggleCheckListButton> {
  bool? _isToggled;
  StreamSubscription? _refreshListener;

  StyleM get _selectionStyle => widget.controller.getSelectionStyle();

  @override
  void initState() {
    super.initState();
    _isToggled = _getIsToggled(_selectionStyle.attributes);
    _subscribeToRefreshListener();
  }

  @override
  void dispose() {
    _refreshListener?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return widget.childBuilder(
      context,
      AttributesAliasesM.unchecked,
      widget.icon,
      widget.buttonsSpacing,
      widget.fillColor,
      _isToggled,
      _toggleAttribute,
      widget.iconSize,
      widget.iconTheme,
    );
  }

  @override
  void didUpdateWidget(covariant ToggleCheckListButton oldWidget) {
    super.didUpdateWidget(oldWidget);

    // If a new controller was generated by setState() in the parent
    // we need to subscribe to the new state store.
    if (oldWidget.controller != widget.controller) {
      _refreshListener?.cancel();
      widget.controller.setStateInEditorStateReceiver(widget);
      _subscribeToRefreshListener();
      _isToggled = _getIsToggled(_selectionStyle.attributes);
    }
  }

  // === PRIVATE ===

  void _subscribeToRefreshListener() {
    _refreshListener = widget._state.refreshEditor.refreshEditor$.listen(
      (_) => _didChangeEditingValue(),
    );
  }

  void _didChangeEditingValue() {
    setState(() {
      _isToggled = _getIsToggled(
        widget.controller.getSelectionStyle().attributes,
      );
    });
  }

  bool _getIsToggled(Map<String, AttributeM> attrs) {
    var attribute =
        widget.controller.toolbarButtonToggler[AttributesM.list.key];

    if (attribute == null) {
      attribute = attrs[AttributesM.list.key];
    } else {
      // Checkbox tapping causes controller.selection to go to offset 0
      widget.controller.toolbarButtonToggler.remove(AttributesM.list.key);
    }

    if (attribute == null) {
      return false;
    }

    return attribute.value == AttributesAliasesM.unchecked.value ||
        attribute.value == AttributesAliasesM.checked.value;
  }

  void _toggleAttribute() {
    widget.controller.formatSelection(
      _isToggled!
          ? AttributeUtils.clone(AttributesAliasesM.unchecked, null)
          : AttributesAliasesM.unchecked,
    );
  }
}
