import 'dart:async';

import 'package:flutter/material.dart';

import '../../controller/controllers/editor-controller.dart';
import '../../documents/models/attribute.model.dart';
import '../../documents/models/style.model.dart';
import '../models/editor-icon-theme.model.dart';
import '../state/editor-state-receiver.dart';
import '../state/editor.state.dart';

// The dropdown presents users a list of options that can be assigned to the edited attribute in text.
// The dropdown value updates based on the selected text value of the edit attribute.
// An initial value can be defined.
// ignore: must_be_immutable
class EditorDropdown<T> extends StatefulWidget with EditorStateReceiver {
  final double iconSize;
  final double? width;
  final Color? fillColor;
  final double hoverElevation;
  final double highlightElevation;
  final T initialValue;
  final Map<String, T> options;
  final ValueChanged<T> onSelected;
  final EditorIconThemeM? iconTheme;
  final AttributeM attribute;
  final EditorController controller;

  // Used internally to retrieve the state from the EditorController instance to which this button is linked to.
  // Can't be accessed publicly (by design) to avoid exposing the internals of the library.
  late EditorState _state;

  @override
  void setState(EditorState state) {
    _state = state;
  }

  EditorDropdown({
    required this.initialValue,
    required this.options,
    required this.attribute,
    required this.controller,
    required this.onSelected,
    this.iconSize = 40,
    this.width,
    this.fillColor,
    this.hoverElevation = 1,
    this.highlightElevation = 1,
    this.iconTheme,
    Key? key,
  }) : super(key: key) {
    controller.setStateInEditorStateReceiver(this);
  }

  @override
  _EditorDropdownState<T> createState() => _EditorDropdownState<T>();
}

class _EditorDropdownState<T> extends State<EditorDropdown<T>> {
  String _selectedOptionId = '';
  StreamSubscription? _refreshListener;

  StyleM get _selectionStyle => widget.controller.getSelectionStyle();

  @override
  void initState() {
    super.initState();
    _subscribeToRefreshListener();
    _selectedOptionId = _getOptionKeyByValue(widget.initialValue);
  }

  @override
  void dispose() {
    _refreshListener?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => _rectangleButton(
        child: _textAndArrow(),
      );

  @override
  void didUpdateWidget(covariant EditorDropdown<T> oldWidget) {
    super.didUpdateWidget(oldWidget);

    // If a new controller was generated by setState() in the parent
    // we need to subscribe to the new state store.
    if (oldWidget.controller != widget.controller) {
      _refreshListener?.cancel();
      widget.controller.setStateInEditorStateReceiver(widget);
      _subscribeToRefreshListener();
    }
  }

  // TODO Update the styling
  Widget _rectangleButton({required Widget child}) => ConstrainedBox(
        constraints: BoxConstraints.tightFor(
          height: widget.iconSize * 1.81,
          width: widget.width ?? 50,
        ),
        child: RawMaterialButton(
          visualDensity: VisualDensity.compact,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(
              widget.iconTheme?.borderRadius ?? 2,
            ),
          ),
          fillColor: widget.fillColor,
          elevation: 0,
          hoverElevation: widget.hoverElevation,
          highlightElevation: widget.hoverElevation,
          onPressed: _displayOptionsMenu,
          child: child,
        ),
      );

  Widget _textAndArrow() {
    final theme = Theme.of(context);

    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Text(
          _selectedOptionId.toString(),
          style: TextStyle(
            fontSize: widget.iconSize / 1.15,
            color:
                widget.iconTheme?.iconUnselectedColor ?? theme.iconTheme.color,
          ),
        ),
        const SizedBox(
          width: 3,
        ),
        Icon(
          Icons.arrow_drop_down,
          size: widget.iconSize / 1.15,
          color: widget.iconTheme?.iconUnselectedColor ?? theme.iconTheme.color,
        )
      ],
    );
  }

  // === PRIVATE ===

  void _subscribeToRefreshListener() {
    _refreshListener = widget._state.refreshEditor.refreshEditor$.listen(
      (_) => _updateSelectedOptionId(),
    );
  }

  // When the editor get refreshed by user interactions we read the text selection
  // and based on it we select the value of the dropdown.
  void _updateSelectedOptionId() {
    setState(
      () => _selectedOptionId = _getSelectedOptionIdFromTextSelection(),
    );
  }

  // Retrieves the value of the edited attribute from the selected text.
  String _getSelectedOptionIdFromTextSelection() {
    final attribute = _selectionStyle.attributes[widget.attribute.key];

    // If no the attribute is not present in the selected text return default value.
    if (attribute == null) {
      return _getOptionKeyByValue(widget.initialValue);

      // If the edited attribute is present and the value is valid get the value.
    } else {
      return _getOptionKeyByValue(attribute.value);
    }
  }

  // Based on the value we want to get the id
  String _getOptionKeyByValue(T value) {
    return widget.options.entries
        .firstWhere(
          (element) => element.value == value,
          // TODO This might no longer work since we have font smaller than the initial implementation "11"
          orElse: () => widget.options.entries.first,
        )
        .key;
  }

  void _displayOptionsMenu() {
    final popupMenuTheme = PopupMenuTheme.of(context);
    final position = _getMenuPosition();

    showMenu<T>(
      context: context,
      elevation: 4,
      initialValue: widget.initialValue,
      items: [
        for (MapEntry<String, T> option in widget.options.entries)
          PopupMenuItem<T>(
            key: ValueKey(option.key),
            value: option.value,
            child: Text(option.key),
          ),
      ],
      position: position,
      shape: popupMenuTheme.shape,
      color: popupMenuTheme.color,
    ).then((newValue) {
      if (!mounted) {
        return null;
      }

      if (newValue == null) {
        return null;
      }

      setState(() {
        _selectedOptionId = widget.options.entries
            .firstWhere(
              (element) => element.value == newValue,
              orElse: () => widget.options.entries.first,
            )
            .key;
        widget.onSelected(newValue);
      });
    });
  }

  RelativeRect _getMenuPosition() {
    final button = context.findRenderObject() as RenderBox;
    final overlay =
        Overlay.of(context)!.context.findRenderObject() as RenderBox;

    return RelativeRect.fromRect(
      Rect.fromPoints(
        button.localToGlobal(
          Offset.zero,
          ancestor: overlay,
        ),
        button.localToGlobal(
          button.size.bottomLeft(Offset.zero),
          ancestor: overlay,
        ),
      ),
      Offset.zero & overlay.size,
    );
  }
}
